// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRlTHuKic-c-ZqBYp8_fe3ih3hcnkmlDc',
    appId: '1:136101478522:web:66564c5e9e6c21eb9c3bc3',
    messagingSenderId: '136101478522',
    projectId: 'leonms-dev',
    authDomain: 'leonms-dev.firebaseapp.com',
    storageBucket: 'leonms-dev.appspot.com',
    measurementId: 'G-LQM3V04Q23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZhvlwF1HtW_6zIKY3MKnsBrCp1I0gjXw',
    appId: '1:136101478522:android:1a7dbf5f6855b9e79c3bc3',
    messagingSenderId: '136101478522',
    projectId: 'leonms-dev',
    storageBucket: 'leonms-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYy3T-dpR0yeikv_GnbZhqQxHk5QFsfGk',
    appId: '1:136101478522:ios:912f51cc931fdb379c3bc3',
    messagingSenderId: '136101478522',
    projectId: 'leonms-dev',
    storageBucket: 'leonms-dev.appspot.com',
    iosClientId:
        '136101478522-fbffniotnpopt0qlqoalq4vi2sn90e3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYy3T-dpR0yeikv_GnbZhqQxHk5QFsfGk',
    appId: '1:136101478522:ios:912f51cc931fdb379c3bc3',
    messagingSenderId: '136101478522',
    projectId: 'leonms-dev',
    storageBucket: 'leonms-dev.appspot.com',
    iosClientId:
        '136101478522-fbffniotnpopt0qlqoalq4vi2sn90e3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnDart',
  );
}
